export default {
  roof1: {
    id: 1,
    name: '小岗村屋顶光伏1',
    address: '安徽省凤阳县小岗村',
    addressDetail: '小溪河镇安阳小区',
    workStatus: '故障停运',
    deviceStatus: '运行',
    dayValue: '30.12',
    monthValue: '231.45',
    totalValue: '1002.92',
    power: '12.31',
    air: '30.1',
    totalPower: '1',
    directPower: '1.1',
    totalUsePower: '1.22',
    totalUselessPower: '1',
    powerFactor: '1.001',
  },
  roof2: {
    id: 1,
    name: '小岗村屋顶光伏2',
    address: '安徽省凤阳县小岗村',
    addressDetail: '小溪河镇安阳小区',
    workStatus: '运行',
    deviceStatus: '运行',
    dayValue: '29.12',
    monthValue: '227.31',
    totalValue: '994.67',
    power: '11.37',
    air: '28.6',
    totalPower: '1',
    directPower: '1',
    totalUsePower: '1',
    totalUselessPower: '1',
    powerFactor: '1.003',
  },
};
