apiVersion: v1
kind: Service
metadata:
  labels:
    cattle.io/creator: norman
  name: xgcsgs-fe-web
  namespace: xgcsgs
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: deployment-xgcsgs-xgcsgs-fe-web
  type: NodePort
