export default {
  dataLoist: [
    {
      id: 1,
      name: '小岗村小溪河镇充电桩1',
      address: '安徽省凤阳县小岗村河溪镇安阳小区',
      workStatus: '充电中',
      currentSoc: '96%',
      dcVoltage: '220V',
      dcElectricity: '120A',
      chargingPower: '10KW',
      waring: '正常',
      breakdown: '正常',
    },
    {
      id: 2,
      name: '小岗村小溪河镇充电桩2',
      address: '安徽省凤阳县小岗村河溪镇安阳小区',
      workStatus: '充电中',
      currentSoc: '96%',
      dcVoltage: '220V',
      dcElectricity: '120A',
      chargingPower: '10KW',
      waring: '当前环境温度过高',
      breakdown: '枪温异常',
    },
    {
      id: 3,
      name: '小岗村小溪河镇充电桩3',
      address: '安徽省凤阳县小岗村河溪镇安阳小区',
      workStatus: '充电中',
      currentSoc: '96%',
      dcVoltage: '220V',
      dcElectricity: '120A',
      chargingPower: '10KW',
      waring: '正常',
      breakdown: '正常',
    },
    {
      id: 4,
      name: '小岗村小溪河镇充电桩4',
      address: '安徽省凤阳县小岗村河溪镇安阳小区',
      workStatus: '充电中',
      currentSoc: '96%',
      dcVoltage: '220V',
      dcElectricity: '120A',
      chargingPower: '10KW',
      waring: '当前环境温度过高',
      breakdown: '枪温异常',
    },
  ],
};

