export default {
  dataList: [
    {
      id: 1,
      name: '小岗村入户光伏',
      address: '安徽省凤阳县小岗村河溪镇安阳小区',
      dailyOutput: '23.6kwh',
      grossGeneration: '241.1kwh',
      outputRating: '12.3kw',
      totalRunningTime: '256h',
      temperature: '35.1',
      powerMeter: '1w',
      workStatus: '运行',
      deviceStatus: '运行',
      warningTime: '',
      warningInfo: '',
    },
    {
      id: 2,
      name: '凤阳县小岗村久华小区入户光伏',
      address: '安徽省凤阳县小岗村河溪镇久华小区',
      dailyOutput: '22.61wh',
      grossGeneration: '239.3kwh',
      outputRating: '11.9kw',
      totalRunningTime: '213h',
      temperature: '32.4',
      powerMeter: '1w',
      workStatus: '运行',
      deviceStatus: '故障停机',
      warningTime: '2021-03-18 17:49:07',
      warningInfo: '小岗村久华入户光伏逆变器检测到电网电压过低',
    },
    {
      id: 3,
      name: '小岗村凤凰城小区光伏',
      address: '安徽省凤阳县小岗村凤凰城小区',
      dailyOutput: '25.1kwh',
      grossGeneration: '249.5kwh',
      outputRating: '14.1kw',
      totalRunningTime: '256h',
      temperature: '33.2',
      powerMeter: '1w',
      workStatus: '运行',
      deviceStatus: '运行',
    },
    {
      id: 4,
      name: '小岗村小溪河镇世府光伏',
      address: '安徽省凤阳县小岗村河溪镇世府小区',
      dailyOutput: '24.4kwh',
      grossGeneration: '233.6kwh',
      outputRating: '15.7kw',
      totalRunningTime: '206h',
      temperature: '33.7',
      powerMeter: '1w',
      workStatus: '运行',
      deviceStatus: '故障停机',
      warningTime: '2021-03-18 11:44:17',
      warningInfo: '世府小区入户光伏逆变器检测到电网电压过低',
    },
    {
      id: 5,
      name: '小溪河镇春景园小区入户光伏',
      address: '安徽省凤阳县小岗村河溪镇春景园春景园',
      dailyOutput: '21.3kwh',
      grossGeneration: '214.2kwh',
      outputRating: '10.3kw',
      totalRunningTime: '221h',
      temperature: '30.3',
      powerMeter: '1w',
      workStatus: '运行',
      deviceStatus: '故障停机',
      warningTime: '2021-03-18 09:55:25',
      warningInfo: '春景园小区入户光伏逆变器检测到电网电压过低',
    },
    {
      id: 6,
      name: '小岗村蔡庄小区入户光伏',
      address: '安徽省凤阳县小岗村河溪镇蔡庄小区',
      dailyOutput: '26.1kwh',
      grossGeneration: '255.7wh',
      outputRating: '15.2kw',
      totalRunningTime: '282h',
      temperature: '30.2',
      powerMeter: '1w',
      workStatus: '运行',
      deviceStatus: '运行',
    },
    {
      id: 7,
      name: '凤阳县中都南苑小区入户光伏',
      address: '安徽省凤阳县小岗村河溪镇中都南苑小区',
      dailyOutput: '23.6kwh',
      grossGeneration: '241.1kwh',
      outputRating: '12.3kw',
      totalRunningTime: '256h',
      temperature: '35.1',
      powerMeter: '1w',
      workStatus: '运行',
      deviceStatus: '故障停机',
    },
    {
      id: 8,
      name: '小岗村御苑小区光伏',
      address: '安徽省凤阳县小岗村河溪镇御苑小区',
      dailyOutput: '28.8kwh',
      grossGeneration: '289.4kwh',
      outputRating: '16.6kw',
      totalRunningTime: '282h',
      temperature: '33.5',
      powerMeter: '1w',
      workStatus: '运行',
      deviceStatus: '运行',
    },
    {
      id: 9,
      name: '小岗村小溪河镇光伏',
      address: '安徽省凤阳县小岗村河溪镇桥西安置小区',
      dailyOutput: '22.3kwh',
      grossGeneration: '229.5kwh',
      outputRating: '12.8kw',
      totalRunningTime: '261h',
      temperature: '36.4',
      powerMeter: '1w',
      workStatus: '运行',
      deviceStatus: '故障停机',
      warningTime: '2021-03-17 18:42:44',
      warningInfo: '桥西安置小区入户光伏逆变器检测到电网电压过低',
    },
    {
      id: 10,
      name: '小溪河社区入户光伏',
      address: '安徽省凤阳县小岗村河溪社区',
      dailyOutput: '27.3kwh',
      grossGeneration: '274.8kwh',
      outputRating: '15.5kw',
      totalRunningTime: '274h',
      temperature: '34.2',
      powerMeter: '1w',
      workStatus: '运行',
      deviceStatus: '运行',
    },
  ],
};

