export default {
  dataList: [
    {
      id: 1,
      name: '小岗村入户光伏',
      address: '安徽省凤阳县小岗村河溪镇安阳小区',
      dailyOutput: '23.6kwh',
      grossGeneration: '241.1kwh',
      outputRating: '12.3kw',
      totalRunningTime: '256h',
      temperature: '35.1',
      powerMeter: '1w',
      workStatus: '运行',
      deviceStatus: '故障停机',
      warning: '2021-03-18 17:49:07 小岗村入户光伏逆变器检测到电网电压过低',
    },
    {
      id: 2,
      name: '凤阳县小岗村入户光伏',
      address: '安徽省凤阳县小岗村河溪镇安阳小区',
      dailyOutput: '23.6kwh',
      grossGeneration: '241.1kwh',
      outputRating: '12.3kw',
      totalRunningTime: '256h',
      temperature: '35.1',
      powerMeter: '1w',
      workStatus: '运行',
      deviceStatus: '故障停机',
      warning: '2021-03-18 17:49:07 小岗村入户光伏逆变器检测到电网电压过低',
    },
    {
      id: 3,
      name: '小岗村安阳小区光伏',
      address: '安徽省凤阳县小岗村河溪镇安阳小区',
      dailyOutput: '23.6kwh',
      grossGeneration: '241.1kwh',
      outputRating: '12.3kw',
      totalRunningTime: '256h',
      temperature: '35.1',
      powerMeter: '1w',
      workStatus: '运行',
      deviceStatus: '故障停机',
      warning: '2021-03-18 17:49:07 小岗村入户光伏逆变器检测到电网电压过低',
    },
    {
      id: 4,
      name: '小岗村小溪河镇光伏',
      address: '安徽省凤阳县小岗村河溪镇安阳小区',
      dailyOutput: '23.6kwh',
      grossGeneration: '241.1kwh',
      outputRating: '12.3kw',
      totalRunningTime: '256h',
      temperature: '35.1',
      powerMeter: '1w',
      workStatus: '运行',
      deviceStatus: '故障停机',
      warning: '2021-03-18 17:49:07 小岗村入户光伏逆变器检测到电网电压过低',
    },
    {
      id: 5,
      name: '小溪河镇入户光伏',
      address: '安徽省凤阳县小岗村河溪镇安阳小区',
      dailyOutput: '23.6kwh',
      grossGeneration: '241.1kwh',
      outputRating: '12.3kw',
      totalRunningTime: '256h',
      temperature: '35.1',
      powerMeter: '1w',
      workStatus: '运行',
      deviceStatus: '故障停机',
      warning: '2021-03-18 17:49:07 小岗村入户光伏逆变器检测到电网电压过低',
    },
    {
      id: 6,
      name: '小岗村入户光伏',
      address: '安徽省凤阳县小岗村河溪镇安阳小区',
      dailyOutput: '23.6kwh',
      grossGeneration: '241.1kwh',
      outputRating: '12.3kw',
      totalRunningTime: '256h',
      temperature: '35.1',
      powerMeter: '1w',
      workStatus: '运行',
      deviceStatus: '故障停机',
      warning: '2021-03-18 17:49:07 小岗村入户光伏逆变器检测到电网电压过低',
    },
    {
      id: 7,
      name: '凤阳县小岗村入户光伏',
      address: '安徽省凤阳县小岗村河溪镇安阳小区',
      dailyOutput: '23.6kwh',
      grossGeneration: '241.1kwh',
      outputRating: '12.3kw',
      totalRunningTime: '256h',
      temperature: '35.1',
      powerMeter: '1w',
      workStatus: '运行',
      deviceStatus: '故障停机',
      warning: '2021-03-18 17:49:07 小岗村入户光伏逆变器检测到电网电压过低',
    },
    {
      id: 8,
      name: '小岗村安阳小区光伏',
      address: '安徽省凤阳县小岗村河溪镇安阳小区',
      dailyOutput: '23.6kwh',
      grossGeneration: '241.1kwh',
      outputRating: '12.3kw',
      totalRunningTime: '256h',
      temperature: '35.1',
      powerMeter: '1w',
      workStatus: '运行',
      deviceStatus: '故障停机',
      warning: '2021-03-18 17:49:07 小岗村入户光伏逆变器检测到电网电压过低',
    },
    {
      id: 9,
      name: '小岗村小溪河镇光伏',
      address: '安徽省凤阳县小岗村河溪镇安阳小区',
      dailyOutput: '23.6kwh',
      grossGeneration: '241.1kwh',
      outputRating: '12.3kw',
      totalRunningTime: '256h',
      temperature: '35.1',
      powerMeter: '1w',
      workStatus: '运行',
      deviceStatus: '故障停机',
      warning: '2021-03-18 17:49:07 小岗村入户光伏逆变器检测到电网电压过低',
    },
    {
      id: 10,
      name: '小溪河镇入户光伏',
      address: '安徽省凤阳县小岗村河溪镇安阳小区',
      dailyOutput: '23.6kwh',
      grossGeneration: '241.1kwh',
      outputRating: '12.3kw',
      totalRunningTime: '256h',
      temperature: '35.1',
      powerMeter: '1w',
      workStatus: '运行',
      deviceStatus: '故障停机',
      warning: '2021-03-18 17:49:07 小岗村入户光伏逆变器检测到电网电压过低',
    },
  ],
};

